spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo?schema=demo
spring.datasource.username=postgres
spring.datasource.password=XlQIppEarQ6
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#commented due to bug, see --> https://stackoverflow.com/questions/77385146/springboot-docker-error-cannot-invoke-dockercliinspectresponse-hostconfig-b
#spring.docker.compose.enabled=true
#spring.docker.compose.file=docker-compose.yml

logging.level.com.example=debug