spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo?schema=demo
spring.datasource.username=postgres
spring.datasource.password=XlQIppEarQ6
spring.datasource.driverClassName=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.com.example=debug

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# JWT Security Configuration
jwt.issuer=https://demo.example.com
jwt.audience=demo-api
jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoT2cMacWevnPpfSolENMP2ePpHHqBxWS419kgzaXxHmd0CLMGn3S0UiBJXahGOZTcdcSEYEXvnyCX0Onq4EILJMj7FTec7EaadwzCLiLqL2Ws2MPWsn9Mr2aLILlV/3y8ITmAlR5yKBJBHO1ezA3RwQ8okKRlX7AVKi7TFydC82DLrbaeOC7X5UVpTW0GcQZyxtMsd4qJhKgOetJq6zYTbvXzJBLqWINy8Zmost8rUe60Y9pfK9nWdU6WB2N22IneuoeL4tzKqZkIxM8qtkQiHX0JXAvxqyGZZ4xMOYN9qovd2MaXKwvQN6EuKFyStUfx6c4QktWajBlLjgAWurr0QIDAQAB

